services:
  archon-frontend:
    image: gordov1su4/archon-frontend:v2.3
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - ARCHON_MCP_PORT=${ARCHON_MCP_PORT:-443}
      - HOST=0.0.0.0
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.archon-frontend.rule=Host(`archon.v1su4.com`) && PathPrefix(`/`)
      - traefik.http.routers.archon-frontend.entryPoints=https
      - traefik.http.routers.archon-frontend.tls=true
      - traefik.http.routers.archon-frontend.tls.certresolver=letsencrypt
      - traefik.http.services.archon-frontend.loadbalancer.server.port=3737

  archon-server:
    image: gordov1su4/archon-server:v6.1
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
      - ARCHON_SERVER_PORT=8181
      - ARCHON_MCP_PORT=8051
      - ARCHON_AGENTS_PORT=8052
      - MCP_CONTAINER_PREFIX=archon-mcp
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.archon-server.rule=Host(`archon.v1su4.com`) && (PathPrefix(`/api`) || PathPrefix(`/socket.io`) || Path(`/health`))
      - traefik.http.routers.archon-server.entryPoints=https
      - traefik.http.routers.archon-server.tls=true
      - traefik.http.routers.archon-server.tls.certresolver=letsencrypt
      - traefik.http.services.archon-server.loadbalancer.server.port=8181

  archon-mcp:
    image: gordov1su4/archon-mcp:v2.2
    container_name: archon-mcp
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - API_SERVICE_URL=http://archon-server:8181
      - AGENTS_SERVICE_URL=http://archon-agents:8052
      - ARCHON_MCP_PORT=8051
      - ARCHON_SERVER_PORT=8181
      - ARCHON_AGENTS_PORT=8052
    depends_on:
      - archon-server
      - archon-agents
    restart: unless-stopped
    labels:
      - traefik.enable=true
      # Route both /mcp and /mcp/sse to the MCP server
      - traefik.http.routers.archon-mcp.rule=Host(`archon.v1su4.com`) && (PathPrefix(`/mcp`) || Path(`/mcp/sse`))
      - traefik.http.routers.archon-mcp.entryPoints=https
      - traefik.http.routers.archon-mcp.tls=true
      - traefik.http.routers.archon-mcp.tls.certresolver=letsencrypt
      # Strip /mcp prefix so /mcp/sse becomes /sse at the container
      - traefik.http.middlewares.archon-mcp-strip.stripprefix.prefixes=/mcp
      - traefik.http.routers.archon-mcp.middlewares=archon-mcp-strip
      - traefik.http.services.archon-mcp.loadbalancer.server.port=8051

  archon-agents:
    image: gordov1su4/archon-agents:v2.1
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
      - ARCHON_AGENTS_PORT=8052
      - ARCHON_SERVER_PORT=8181
    restart: unless-stopped
    labels:
      - traefik.enable=false
