version: '3'

services:
  archon-server:
    image: gordov1su4/archon-server:v1.0
    ports:
      - "8181:8181"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
      - ARCHON_SERVER_PORT=8181
      - ARCHON_MCP_PORT=8051
      - ARCHON_AGENTS_PORT=8052
    restart: unless-stopped

  archon-mcp:
    image: gordov1su4/archon-mcp:v1.0
    ports:
      - "8051:8051"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - API_SERVICE_URL=http://archon-server:8181
      - AGENTS_SERVICE_URL=http://archon-agents:8052
      - ARCHON_MCP_PORT=8051
    depends_on:
      - archon-server
      - archon-agents
    restart: unless-stopped

  archon-agents:
    image: gordov1su4/archon-agents:v1.0
    ports:
      - "8052:8052"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
      - ARCHON_AGENTS_PORT=8052
    restart: unless-stopped

  archon-frontend:
    image: gordov1su4/archon-frontend:v1.0
    ports:
      - "3737:3737"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8181}
      - VITE_ARCHON_SERVER_PORT=8181
      - ARCHON_SERVER_PORT=8181
      - HOST=0.0.0.0
    depends_on:
      - archon-server
    restart: unless-stopped
