services:
  # Archon Server Service (FastAPI + Socket.IO + Crawling)
  archon-server:
    image: gordov1su4/archon-server:latest
    container_name: archon-server
    ports:
      - "8181:8181"
    environment:
      # Use your existing Supabase database
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - LOG_LEVEL=INFO
      - ARCHON_SERVER_PORT=8181
      - ARCHON_MCP_PORT=8051
      - ARCHON_AGENTS_PORT=8052
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
    restart: unless-stopped

  # Archon MCP Server Service
  archon-mcp:
    image: gordov1su4/archon-mcp:latest
    container_name: archon-mcp
    ports:
      - "8051:8051"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - API_SERVICE_URL=http://archon-server:8181
      - AGENTS_SERVICE_URL=http://archon-agents:8052
      - ARCHON_MCP_PORT=8051
    depends_on:
      - archon-server
      - archon-agents
    networks:
      - default
    restart: unless-stopped

  # Archon Agents Service
  archon-agents:
    image: gordov1su4/archon-agents:latest
    container_name: archon-agents
    ports:
      - "8052:8052"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - LOG_LEVEL=INFO
      - ARCHON_AGENTS_PORT=8052
    networks:
      - default
    restart: unless-stopped

  # Archon Frontend UI
  archon-frontend:
    image: gordov1su4/archon-frontend:latest
    container_name: archon-ui
    ports:
      - "3737:3737"
    environment:
      - VITE_API_URL=http://localhost:8181
      - VITE_ARCHON_SERVER_PORT=8181
      - ARCHON_SERVER_PORT=8181
      - HOST=localhost
    depends_on:
      - archon-server
    networks:
      - default
    restart: unless-stopped

networks:
  default:
