version: '3.8'

services:
  # Archon Server Service (FastAPI + Socket.IO + Crawling)
  archon-server:
    image: gordov1su4/archon-server:latest
    container_name: archon-server
    ports:
      - "8181:8181"
    environment:
      # Replace these with your actual values in Coolify
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
      - ARCHON_SERVER_PORT=8181
      - ARCHON_MCP_PORT=8051
      - ARCHON_AGENTS_PORT=8052
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - archon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Archon MCP Server Service
  archon-mcp:
    image: gordov1su4/archon-mcp:latest
    container_name: archon-mcp
    ports:
      - "8051:8051"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - API_SERVICE_URL=http://archon-server:8181
      - AGENTS_SERVICE_URL=http://archon-agents:8052
      - ARCHON_MCP_PORT=8051
    depends_on:
      - archon-server
      - archon-agents
    networks:
      - archon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8051/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Archon Agents Service
  archon-agents:
    image: gordov1su4/archon-agents:latest
    container_name: archon-agents
    ports:
      - "8052:8052"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
      - ARCHON_AGENTS_PORT=8052
    networks:
      - archon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8052/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Archon Frontend UI
  archon-frontend:
    image: gordov1su4/archon-frontend:latest
    container_name: archon-ui
    ports:
      - "3737:3737"
    environment:
      # Update these for your domain
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8181}
      - VITE_ARCHON_SERVER_PORT=8181
      - ARCHON_SERVER_PORT=8181
      - HOST=0.0.0.0
    depends_on:
      - archon-server
    networks:
      - archon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3737"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  archon-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
