name: Deploy MCP Fix to Docker Hub

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-and-push-mcp:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: gordov1su4
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push MCP image
        uses: docker/build-push-action@v5
        with:
          context: ./python
          file: ./python/Dockerfile.mcp
          push: true
          tags: |
            gordov1su4/archon-mcp:v2.1
            gordov1su4/archon-mcp:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
