name: Deprecated - MCP Only Deploy (No-op)

on:
  workflow_dispatch:

jobs:
  noop:
    name: Deprecated workflow (no-op)
    runs-on: ubuntu-latest
    steps:
      - name: Print deprecation notice
        run: |
          echo "This workflow is deprecated. Please use .github/workflows/deploy-coolify.yml"
